@echo off
echo Killing all node processes...
taskkill /f /im node.exe 2>nul
timeout /t 2 /nobreak >nul
echo Removing Next.js lock file...
del /f /q ".next\dev\lock" 2>nul
echo Starting dev server...
npm run dev
